### ISSUE TITLE
could not install open gapp on vmware image

### ISSUE THREAD

**Issue by stevebovy** [FydeOS/overlay-variant-amd64-generic-vmware#17]
[Wed Mar 24 20:27:31 PDT 2021] args: OpenGApps test-network

[Wed Mar 24 20:27:32 PDT 2021] args: OpenGApps prepare
######################################################################## 100.0%

[Wed Mar 24 20:27:35 PDT 2021] args: OpenGApps download - https://downloads.sourceforge.net/project/opengapps/x86_64/20210110/open_gapps-x86_64-9.0-pico-20210110.zip https://fydeos.com/arc-rec/after_hook.sh
######################################################################## 100.0%##O#-#                                                                        
test of /home/chronos/fydeos-arc/zip/update.zip OK
######################################################################## 100.0%

[Wed Mar 24 20:27:46 PDT 2021] args: OpenGApps flash
[-] prepare files
cp: error writing '/home/chronos/fydeos-arc/work_dir/system_rw/system/framework/oat/x86_64/wifi-service.vdex': No space left on device
cp: error writing '/home/chronos/fydeos-arc/work_dir/system_rw/system/framework/okhttp.jar': No
[Wed Mar 24 20:28:06 PDT 2021] args: OpenGApps clear

**Comment by alphato-o** [comment]
Presumably you were asking FydeOS VM for VMWare, however this project only concerns Chromium OS VM.

btw, check out FydeOS VM for VMWare v12, we've fixed the problem.
