### ISSUE TITLE
VM虚拟机运行极其卡顿

### ISSUE THREAD

**Issue by luffyfuture** [FydeOS/overlay-variant-amd64-generic-vmware#19]
官网下载的OVA文件
硬件是NUC11I5
VM为最新版16.2.1
导入运行，鼠标滑动十分卡顿。

**Comment by alphato-o** [comment]
This repo does not concern FydeOS VM. It's Chromium OS VM for VMware.

For support about FydeOS, use [FydeOS Community](https://community.fydeos.com/) or [Telegram group](https://t.me/hi_fydeos).
