### ISSUE TITLE
Expending Partition Size

### ISSUE THREAD

**Issue by hadihashem** [FydeOS/overlay-variant-amd64-generic-vmware#9]
Hello
Expending disk size in VM settings is obviously not enough
Do you know how to expend partitions in Chromium OS to use all available unallocated space?
Regards

**Comment by alphato-o** [comment]
- First, you need to shut down your VM, adjust the vmdk size to your liking within VMWare settings for this Chromium OS VM.

- Then, boot into Chromium OS VM, bring up a shell prompt (ctrl + alt + F2 for tty shell; or ctrl + alt + t for crosh shell then enter `shell` for bash), login with `chronos` / `test0000`

- Execute the `lsblk` command and verify your stateful partition label name, depending on your vmdk settings, it's likely to be `nvme0n1p1`. Make sure it's listed in the output.

- Execute the expansion script:
   ```
   sudo /usr/sbin/expand-partition.sh --dst /dev/nvme0n1p1
   ```
   Once the script finish running without error, your stateful partition should be expanded to occupy the rest of your vmdk free space.

**Comment by hadihashem** [comment]
Works perfectly
Thank you
